simaliar to the first attempt but with cleaner code, more flexible layer creation

In [42]:
import numpy as np
import math
print("start!")


start!


In [43]:
def create_layer(layer_size, dtype=np.float32, **kwargs):
    layer = np.zeros(layer_size, dtype=dtype)
    return(layer)

def create_layer_weights(prev_ly_size, curr_ly_size, init=True):
    if init:
        ly_weights = np.random.rand(prev_ly_size, curr_ly_size)
    else:
        ly_weights = np.zeros(shape=(prev_ly_size, curr_ly_size))
    return(ly_weights)

def create_biases(ly_size):
    biases = np.random.rand(ly_size)
    return(biases)


def create_network(in_ly_size, out_ly_size, hidden_ly_num, hidden_ly_size):
    in_layer = create_layer(in_ly_size)
    hidden_lys = []
    for index in range(hidden_ly_num):
        hidden_lys.append(create_layer(hidden_ly_size))
    out_layer = create_layer(out_ly_size)
    network_lys = [in_layer, *hidden_lys, out_layer]

    biases =[]
    for layers in network_lys:
        biases.append(create_biases(np.size(layers)))

    weights = []
    for i in range(1, len(network_lys), 1):
        weights.append( create_layer_weights(np.size(network_lys[i-1]), np.size(network_lys[i]), init=True))

    return(network_lys, biases, weights)


In [49]:
layers, biases, weights = create_network(5,5,2,7)
for items in layers:
    print(items)
for items in biases:
    print(items)
for items in weights:
    print(weights)

weight1 = weights[1]
print("weights 1:",weight1)
print("weights 1 type:",np.size(weight1))

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0.18138172 0.49133329 0.47194168 0.34946886 0.0179582 ]
[0.36104727 0.41144984 0.12153629 0.81712652 0.4214953  0.7355139
 0.88598537]
[0.0065017  0.27831894 0.3433617  0.91463386 0.5027194  0.91064628
 0.38673936]
[0.35030736 0.8771847  0.8178496  0.22229099 0.62000428]
[array([[0.09755438, 0.48288028, 0.12197114, 0.67768743, 0.49514712,
        0.57279304, 0.20127214],
       [0.12790017, 0.44134544, 0.67803912, 0.52069095, 0.2061815 ,
        0.37310014, 0.12133343],
       [0.83857646, 0.14804932, 0.6656228 , 0.49654839, 0.37260262,
        0.6473751 , 0.90055025],
       [0.21289071, 0.27819067, 0.75820842, 0.04656807, 0.66262075,
        0.74642089, 0.00351615],
       [0.8993933 , 0.76278594, 0.0208679 , 0.24228912, 0.95915823,
        0.30878824, 0.71383237]]), array([[0.60469393, 0.06846336, 0.85606406, 0.31573051, 0.39857643,
        0.12174797, 0.05975147],
       [0.0836085 , 0.13384079, 0.8645