In [14]:
import numpy as np

Al = np.array([1,4,3])
Wl = np.array([
[0,0,1],
[1,1,0],
[1,1,1],
[1,8,0],
[1,1,1]
])

DA = np.zeros(5)
gwight = np.transpose(Wl)

#print(nly)

DA = np.dot(Al, gwight)
print("DA: ", np.dot(Al, gwight))

def label_to_output(input: int):
    outlayer = np.zeros(shape=(10), dtype=np.float32)
    outlayer[input] = 1
    return(outlayer)

def label_vec_to_output(inputs: np.ndarray) -> np.ndarray:
    # Create an identity matrix of size 10 and index into it
    return np.eye(10, dtype=np.int8)[inputs]


label_in = np.array([0,1,2,3,4,5,6,7,8,9,0,1,2,3,4])
print("size of label array: ", np.size(label_in))
Labels = label_vec_to_output(label_in)
print("size of label array: ", np.shape(Labels))
print(Labels)

print(Wl)
Wl = Wl * 0.05
print(Wl)

DA:  [ 3  5  8 33  8]
size of label array:  15
size of label array:  (15, 10)
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]
[[0 0 1]
 [1 1 0]
 [1 1 1]
 [1 8 0]
 [1 1 1]]
[[0.   0.   0.05]
 [0.05 0.05 0.  ]
 [0.05 0.05 0.05]
 [0.05 0.4  0.  ]
 [0.05 0.05 0.05]]


In [25]:
import numpy as np

A = np.random.rand(10,)
A_neg1 = np.random.rand(17,)
print("shape of A: ", A.shape)

print("A neg: ",A_neg1)

W = np.ndarray(shape=(17,10))
W = np.random.rand(17,10)

thingy = np.dot(W, A)
print("shape of product: ",thingy.shape)
thingy_2 = np.outer(A_neg1, A)
print("thingy 2 shape : ", thingy_2.shape)

shape of A:  (10,)
A neg:  [0.67811977 0.28163797 0.51015089 0.42893643 0.31217178 0.92131973
 0.6873461  0.49285303 0.10728521 0.76288248 0.72595143 0.03016806
 0.72768863 0.07856564 0.76650734 0.40069881 0.88243665]
shape of product:  (17,)
thingy 2 shape :  (17, 10)


In [1]:
import numpy as np

# Sample input: list of ndarrays with the same shape
arrays = [
    np.array([[1, 2], [3, 4]]),
    np.array([[5, 6], [7, 8]]),
    np.array([[9, 10], [11, 12]])
]

# Stack them along a new axis and compute the mean across that axis
average = np.mean(arrays, axis=0)

print(average)


[[5. 6.]
 [7. 8.]]


In [6]:
layer_num = 4
for l_num in range(layer_num-1,0,-1):
    w_num = l_num -1
    print("W_num", w_num)    
    print("L_num", l_num)

W_num 2
L_num 3
W_num 1
L_num 2
W_num 0
L_num 1
